AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  BucketNameParameter:
    Type: String
    Description: S3 Bucket Name
    Default: us-east-1-324320755747-jake-bucket-lambda
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketNameParameter
    DeletionPolicy: Delete
